# Generated by Django 5.2.5 on 2025-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('contenu', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_sms', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
